version: '3'

services:
  php:
    volumes: 
      - ./api:/var/www/html
    image: bank-php
    container_name: bank-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - "db"
    networks:
      net:

  ws:
    volumes: 
      - ./api:/var/www/html
    container_name: bank-ws
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8686:80"
    depends_on:
      - "php"
    networks:
      net:

networks:
  net:

volumes:
  db: